In [1]:
import os

print(os.getcwd())

/Users/davideevangelista/calcolo-numerico/Lezioni


In [2]:
path_rel = "./data"
path_abs = "/Users/davideevangelista/calcolo-numerico/Lezioni/data"

print(os.listdir(path_rel))

['esempio.txt', 'day_wise.csv', 'data_hw.csv']


In [3]:
# Consideriamo una cartella "data", e supponiamo di avere al suo interno un file
# "esempio.txt"
data_path = "./data"
file_name = "esempio.txt"

# Costruiamo il percorso per il file
path_file = os.path.join(data_path, file_name)
print(path_file)

# Verifica se il path per il file esiste, se no, costuiamolo
if not os.path.exists(data_path):
    os.makedirs(data_path, exist_ok=True)

# Vediamo se ora esiste
print(os.path.exists(data_path))

./data/esempio.txt
True


In [4]:
import os

# Creiamo una stringa da salvare
s = "Questa stringa contiene informazioni importanti, da tenere in memoria."

# Definiamo il path
path = os.path.join("logs", "nome_file.txt")
os.makedirs("logs", exist_ok=True)

# Apriamo il file
with open(path, mode="w") as f:
    # All'interno del "with" posso lavorare sul file, chiamato "f"
    f.write(s)

# Fuori dal "with", il file è stato chiso

In [5]:
# Andiamo a leggere il contenuto del file appena creato
with open(path, "r") as f:
    s = f.read()
print(s)

Questa stringa contiene informazioni importanti, da tenere in memoria.


In [6]:
import json
import os

# Generiamo un dizionario di esempio
config = {
    "nome_algoritmo": "MetodoDiscesa",
    "parametro1": 10,
    "parametro2": 0.01,
}

# Definiamo il path (come prima)
path = os.path.join("logs", "config.json")

# Apriamo un file json in lettura
with open(path, "w") as f:
    json.dump(config, f)

In [7]:
def divisione(a, b):
    try:
        risultato = a / b
    except ZeroDivisionError:
        print("Errore: divisione per zero non consentita!")
        risultato = None
    return risultato

print(divisione(10, 0))  # Genera errore 10 / 0

Errore: divisione per zero non consentita!
None


In [8]:
import numpy as np

# Creo un vettore numpy
a: list[int] = [1, 2, 3]
a_vec: np.ndarray = np.array(a)
print(type(a_vec)) # Verifichiamo il tipo di dato di a_vec
print(a_vec)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
print(a_vec.shape)

(3,)


In [10]:
# Definiamo un vettore v e una matrice A
v = np.array([1, 1, 3, 2])
A = np.array([[1, 1, -1],
              [0, -1, 1]])

# Stampiamo la shape
print(f"La shape di v è: {v.shape}.")
print(f"La shape di A è: {A.shape}.")

La shape di v è: (4,).
La shape di A è: (2, 3).


In [11]:
# Creiamo un vettore
v = np.array([1, 2, 1.2])
print(v.dtype) # np.float64

# Creiamo lo stesso vettore in precisione singola
v = np.array([1, 2, 1.2], dtype=np.float32)
print(v.dtype)

float64
float32


In [12]:
v = np.linspace(0, 1, 11)
print(v)

z = np.zeros((3,))
print(z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0. 0. 0.]


In [13]:
a = np.random.randn(2, 2)
print(a)

b = np.random.rand(2, 2)
print(b)

[[-1.55088753 -0.8810344 ]
 [ 0.18119844 -0.5942623 ]]
[[0.65768987 0.09456384]
 [0.81680856 0.73217574]]


In [14]:
# Creiamo due ndarray
a = np.array([1, -1, 0])
b = np.linspace(1, 3, 3) # array(1, 2, 3)

# Eseguiamo operazioni tra loro
s = a + b
d = a - b
p = a * b
f = a / b

print(f"a = {a}, b = {b} \nSomma: {s} \nDifferenza: {d} \nProdotto: {p} \nDivisione: {f}.")

a = [ 1 -1  0], b = [1. 2. 3.] 
Somma: [2. 1. 3.] 
Differenza: [ 0. -3. -3.] 
Prodotto: [ 1. -2.  0.] 
Divisione: [ 1.  -0.5  0. ].


In [15]:
# Definiamo una matrice A e un vettore x
A = np.array([[1, 1, 1], [0, -1, 0], [0, 0, 1]])
x = np.array([1, 0, 1])
print(x.shape)

# Calcoliamo y = Ax
y = A@x
print(y)

(3,)
[2 0 1]


In [16]:
x = np.array([1, 0, -1])
print(x.shape)

x_riga = np.array([[1, 0, -1]])
print(x_riga.shape)

x_col = np.array([[1], [0], [-1]])
print(x_col.shape)

(3,)
(1, 3)
(3, 1)


In [17]:
print(A @ x)

[ 0  0 -1]


In [18]:
v = np.linspace(1, 9, 9)
print(v)

A = np.reshape(v, (3, 3))
print(A)

print(A.flatten())

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
# Definiamo tre vettori casuali
a = np.random.rand(5)
b = np.random.rand(5)
c = np.random.rand(5)
print(a)
print(b)
print(c)

# Generiamo il vettore booleano `v` che vale True quando un elemento di `a`
# è maggiore o uguale del corrispettivo elemento di `b`
v = a >= b
print(v)

# E il vettore `w`che vale True quando un elemento di `b` è maggiore o uguale
# del corrispettivo elemento di `c`
w = b >= c
print(w)

# Ora uniamoli con un operazione di `and` elemento per elemento
print(w & v)

[0.68216746 0.24079195 0.11525857 0.13800266 0.34760195]
[0.77761393 0.43743837 0.13780199 0.42225251 0.11687666]
[0.02186662 0.72493175 0.22141061 0.2289169  0.65970736]
[False False False False  True]
[ True False False  True False]
[False False False False False]


In [20]:
# Creiamo un array di esempio
v = np.array([0, 1, -1, 2, 1, -1])
print(v)

# Definiamo un vettore booleano
b = np.array([True, True, False, True, False, False])
print(b)

# Slicing
print(v[b])

[ 0  1 -1  2  1 -1]
[ True  True False  True False False]
[0 1 2]


In [21]:
v = np.random.randn(5)
print(v)
print(v[v < 0])

[ 1.49209062  2.19010805 -0.15253686 -0.75753358  0.57432696]
[-0.15253686 -0.75753358]


In [22]:
# Creiamo la matrice
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A) 

# Slicing
B = A[:2, :2]
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [23]:
import time
import numpy as np
import math

# Costruiamo il vettore
v = np.random.randn(10_000_000)

# || v ||_1 con Python modo 1
start_time = time.time()
norma_1 = 0
for i in range(len(v)):
    norma_1 = norma_1 + abs(v[i])
end_time = time.time()
print(f"Tempo impiegato con Python modo 1: {end_time - start_time}s")

# || v ||_1 con Python modo 2
start_time = time.time()
norma_1 = sum((abs(i) for i in v)) # list comprehension
end_time = time.time()
print(f"Tempo impiegato con Python modo 2: {end_time - start_time}s")

# || v ||_1 con numpy
start_time = time.time()
norma_1 = np.sum(np.abs(v))
end_time = time.time()
print(f"Tempo impiegato con Numpy: {end_time - start_time}s")

Tempo impiegato con Python modo 1: 1.3553111553192139s


Tempo impiegato con Python modo 2: 0.6300599575042725s
Tempo impiegato con Numpy: 0.011284112930297852s
