In [1]:
import numpy as np

# Creo un vettore numpy
a: list[int] = [1, 2, 3]
a_vec: np.ndarray = np.array(a)
print(type(a_vec)) # Verifichiamo il tipo di dato di a_vec
print(a_vec)

<class 'numpy.ndarray'>
[1 2 3]


In [2]:
# Definiamo un vettore v e una matrice A
v = np.array([1, 1, 3, 2])
A = np.array([[1, 1, -1],
              [0, -1, 1]])

# Stampiamo la shape
print(f"La shape di v è: {v.shape}.")
print(f"La shape di A è: {A.shape}.")

La shape di v è: (4,).
La shape di A è: (2, 3).


In [3]:
# Creiamo un vettore
v = np.array([1, 2, 1.2])
print(v.dtype) # np.float64

# Creiamo lo stesso vettore in precisione singola
v = np.array([1, 2, 1.2], dtype=np.float32)
print(v.dtype)

float64
float32


In [4]:
# Creiamo il vettore richiesto
v = np.random.rand(10)
print(v)

[0.53860875 0.13699224 0.13390741 0.88724061 0.19142975 0.60958048
 0.06971019 0.30655518 0.78817803 0.77595642]


In [5]:
# Creiamo due ndarray
a = np.array([1, -1, 0])
b = np.linspace(1, 3, 3) # array(1, 2, 3)

# Eseguiamo operazioni tra loro
s = a + b
d = a - b
p = a * b
f = a / b

print(f"a = {a}, b = {b} \nSomma: {s} \nDifferenza: {d} \nProdotto: {p} \nDivisione: {f}.")

a = [ 1 -1  0], b = [1. 2. 3.] 
Somma: [2. 1. 3.] 
Differenza: [ 0. -3. -3.] 
Prodotto: [ 1. -2.  0.] 
Divisione: [ 1.  -0.5  0. ].


In [6]:
# Definiamo un array
x = np.linspace(0, 2*np.pi, 4)

# Calcoliamone i valori trigonometrici
print(f"sin(x) = {np.sin(x)}.")
print(f"cos(x) = {np.cos(x)}.")
print(f"tan(x) = {np.tan(x)}.")

# Ed esponenziale e logaritmo
print(f"e^x = {np.exp(x)}.")
print(f"ln(x) = {np.log(x + 1)}.")
print(f"log_10(x) = {np.log10(x + 1)}.")

sin(x) = [ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16].
cos(x) = [ 1.  -0.5 -0.5  1. ].
tan(x) = [ 0.00000000e+00 -1.73205081e+00  1.73205081e+00 -2.44929360e-16].
e^x = [  1.           8.1205274   65.9429652  535.49165552].
ln(x) = [0.         1.12959244 1.64650057 1.98556831].
log_10(x) = [0.         0.49057577 0.71506611 0.86232136].


In [7]:
# Definiamo una matrice A e un vettore x
A = np.array([[1, 1, 1], [0, -1, 0], [0, 0, 1]])
x = np.array([1, 0, 1])

# Calcoliamo y = Ax
y = A@x
print(y)

[2 0 1]


In [8]:
# Definiamo due vettori classici
v = np.array([1, -1, 1])
w = np.array([0, 1, 1])
print(v.shape, w.shape) # Controlliamo che siano vettori classici

# Calcoliamone il prodotto scalare
print(v @ w)

# Definiamo la loro versione come vettori colonna
v = np.array([[1], [-1], [1]])
w = np.array([[0], [1], [1]])
print(v.shape, w.shape)

# Calcoliamone il prodotto scalare
print(v @ w)

(3,) (3,)
0
(3, 1) (3, 1)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [9]:
# Definiamo tre vettori casuali
a = np.random.rand(10)
b = np.random.rand(10)
c = np.random.rand(10)

# Generiamo il vettore booleano `v` che vale True quando un elemento di `a`
# è maggiore o uguale del corrispettivo elemento di `b`
v = a >= b
print(v)

# E il vettore `w`che vale True quando un elemento di `b` è maggiore o uguale
# del corrispettivo elemento di `c`
w = b >= c
print(w)

# Ora uniamoli con un operazione di `and` elemento per elemento
print(w & v)

[False False False False False False  True  True  True False]
[ True  True  True  True False  True  True False False False]
[False False False False False False  True False False False]


In [10]:
# Definiamo un array
v = np.array([0, 1, -1, 2, 1, -1])

# Slicing
w = v[0:3]
print(w)

[ 0  1 -1]


In [11]:
# Creiamo un array di esempio
v = np.array([0, 1, -1, 2, 1, -1])
print(v)

# Definiamo un vettore booleano
b = np.array([True, True, False, True, False, False])
print(b)

# Slicing
print(v[b])

[ 0  1 -1  2  1 -1]
[ True  True False  True False False]
[0 1 2]


In [12]:
# Definiamo un vettore casuale
x = np.random.randn(8)
print(x)

# Proiettiamo sull'asse positivo
x[x < 0] = 0
print(x)

[-0.80166815  0.93414683  0.62817759 -0.21499552 -0.22965556 -0.5291032
 -0.85889971 -0.30573981]
[0.         0.93414683 0.62817759 0.         0.         0.
 0.         0.        ]


In [13]:
# Creiamo la matrice
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
B = A[:2, :2]
print(B)

[[1 2]
 [4 5]]


In [14]:
# Definiamo un vettore v
v = np.linspace(1, 9, 9) # (1, 2, 3, ..., 9)
print(v)

# E costruiamo la matrice A di shape 3x3 ottenuta modificando v
A = np.reshape(v, (3, 3))
print(A)

# Controlliamo se A è di rango massimo
print(np.linalg.matrix_rank(A))

# E, se ha rango massimo, calcoliamone l'inversa
if np.linalg.matrix_rank(A) == A.shape[0]:
    A_inv = np.linalg.inv(A)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2


In [15]:
import time
import numpy as np
import math

# Costruiamo il vettore
v = np.random.randn(10_000_000)

# || v ||_1 con Python modo 1
start_time = time.time()
norma_1 = 0
for i in range(len(v)):
    norma_1 = norma_1 + abs(v[i])
end_time = time.time()
print(f"Tempo impiegato con Python modo 1: {end_time - start_time}s")

# || v ||_1 con Python modo 2
start_time = time.time()
norma_1 = sum((abs(i) for i in v)) # list comprehension
end_time = time.time()
print(f"Tempo impiegato con Python modo 2: {end_time - start_time}s")

# || v ||_1 con numpy
start_time = time.time()
norma_1 = np.sum(np.abs(v))
end_time = time.time()
print(f"Tempo impiegato con Numpy: {end_time - start_time}s")

Tempo impiegato con Python modo 1: 0.9546482563018799s


Tempo impiegato con Python modo 2: 0.5896708965301514s
Tempo impiegato con Numpy: 0.01151275634765625s
